### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by TBog** [basiclines/GooglePlay-JSAPI#12]
The playstore html class names seem to be obfuscated. Any way to fix this?

**Comment by basiclines** [comment]
Looks like there has been a lot of changes yes. This will require a lot of work to re-do some of the scrapping in this old and  rusty project. I guess we will need to find to ways to match aria-roles and similar attributes as selectors which looks like are more safer to use.

**Comment by TBog** [comment]
I found a working scraper [here](https://github.com/facundoolano/google-play-scraper) and tried to make it work on heroku on this [branch](https://github.com/TBog/google-play-scraper/tree/heroku)
example: https://playstore-jsapi.herokuapp.com/app/rocks.tbog.tblauncher

**Comment by basiclines** [comment]
Looking as a good alternative to this projects as seems is much more frequently updated!

**Comment by TBog** [comment]
The issue I have is that the app version is not working properly. What I wanted was a way to get a [shield](http://shields.io/) with the app version

**Comment by TBog** [comment]
Thanks for all the help (mostly the Heroku deploy and port listening).
This is what I ended up with: ![play-store shield](https://img.shields.io/endpoint?url=https%3A%2F%2Fplaystore-jsapi.herokuapp.com%2Fsep%2Fcom.supercell.clashofclans)
My app is still in beta and probably the reason for the lack of version: ![TinyBit Launcher shield](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fplaystore-jsapi.herokuapp.com%2Fsep%2Frocks.tbog.tblauncher)
