### ISSUE TITLE
averageUserRating and userRatingCount don't match

### ISSUE THREAD

**Issue by DarkyX** [basiclines/GooglePlay-JSAPI#6]
HI.
I tried with a lot of apps, but some doesn’t match well.  

http://googleplay-jsapi.herokuapp.com/app/com.facebook.katana

The result is:
"averageUserRating":3,"userRatingCount":"33"
In Google play the rating is 4 and rating count 33.981.176

**Comment by basiclines** [comment]
Fixed with https://github.com/basiclines/GooglePlay-JSAPI/pull/11
